services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    links:
      - db
    depends_on:
      - db
    ports:
      - 5454:5454
    environment:
      - PGADMIN_DEFAULT_EMAIL=${FLASK_APP_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${FLASK_APP_PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5454
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
    name: pgadmin-data