services:
  web:
    container_name: flask
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: /app/app.py
  db:
    container_name: postgres
    hostname: postgres-host
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${FLASK_APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FLASK_APP_POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: postgres-data
networks:
  default:
    name: app-network